version: "3.8"
services:
  ms-nestjs:
    container_name: ms-nestjs
    build:
      dockerfile: Dockerfile
      context: .
    restart: on-failure
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - db

networks:
  db:
    external:
      name: db-network