version: "3.8"
services:
  ms-nestjs:
    container_name: ms-nestjs
    build:
      dockerfile: Dockerfile
      context: .
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:asd789@postgres-dev:5432/db
    env_file:
      - .env
    networks:
      - db

networks:
  db:
    external:
      name: db-network